### ISSUE TITLE
Issues with compilation

### ISSUE THREAD

**Issue by MotleyDrue** [horack/esp8266_arduino_temperature_nodes#1]
Great write up -- Found you after an excellent review on Amazon of the NodeMCU Board . I am having some issues and I was hoping you might be able to help a novice such as myself. I think I have added all the correct libraries but when I try to compile and submit to the board I get an error line @

 include <memory>

Not sure what the deal is but any direction would be awesome!

Best,
Drew

**Comment by horack** [comment]
Fixed. Had to add D pin definitions and switch the Adafruit DHT library from unified to plain.
